### ISSUE TITLE
"Floating point exception" on typing an undefined command

### ISSUE THREAD

**Issue by apt1002** [rrthomas/pforth#15] opened 2019-04-24 22:44 UTC
```
apt1002@hen:~/rrthomas/pforth/src/smite$ git status
On branch smite-instruction-set-changes
Your branch is up-to-date with 'origin/smite-instruction-set-changes'.

nothing to commit, working tree clean
apt1002@hen:~/rrthomas/pforth/src/smite$ smite pforth-base 
pForth v0.80 (platform: SMite)
(c) Reuben Thomas 1991-2019

sdfdsfsdf
Floating point exception
```

In other respects it seems to work fine!

**Comment by rrthomas** [comment] 2019-04-25 23:00
Fixed in merge-apt-fixes; this bug was caused by a combination of two bugs in SMite.

**Closed as completed by rrthomas** 2019-04-25 23:00 UTC
